Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        public string Id { get; set; }
        public string Nome { get; set; }
        public string? Descrizione { get; set; }

        public string? ImgPath { get; set; }

        public string Prezzo { get; set; }
    }

    public class listaPizze
    {
        public List<Pizza> pizzas { get; set; }
        public listaPizze()
        {
            pizzas = new List<Pizza>();
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Index2()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using la_mia_pizzeria_static.Models;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        public static listaPizze pizze;
        public IActionResult Index()
        {
            pizze = new listaPizze();

            Pizza pizza1 = new Pizza()
            {
                Id = "1",
                Nome = "Margherita",
                Descrizione = "Pizza con mozzarella e pomodoro",
                ImgPath = "/img/pizza1.jpg",
                Prezzo = "5.00"

            };

            pizze.pizzas.Add(pizza1);

            Pizza pizza2 = new Pizza()
            {
                Id = "2",
                Nome = "Filetto",
                Descrizione = "Pizza con pomodorini tagliatti a fette",
                ImgPath = "/img/pizza2.jpg",
                Prezzo = "7.00"

            };

            pizze.pizzas.Add(pizza2);

            Pizza pizza3 = new Pizza()
            {
                Id = "3",
                Nome = "Al salame",
                Descrizione = "Pizza con fette di salame",
                ImgPath = "/img/pizza3.jpg",
                Prezzo = "6.50"

            };

            pizze.pizzas.Add(pizza3);

            return View(pizze);
        }


        public IActionResult Show(int id)
        {
            foreach (var ele in pizze.pizzas)
            {
                if (ele.Id == Convert.ToString(id)) { return View("Show", pizze.pizzas[id - 1]); }

            }

            return NotFound(" La pizza con l'id " + id + " non è stato trovato ");

        }
    }
}

Views/Home/Index.cshtml
@{  Layout = null;
    ViewData["Title"] = "Home Page";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />

</head>
<body>

    <header class="navbar navbar-light bg-white border-bottom box-shadow mb-3">

                <h1 class="mb-3">Scegli la tua pizza : </h1>
    </header>
    
         <div class="container" style="height=80vh">
            <main role="main" class="pb-3">

                <div class="row">

                <div class="col" >
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza1.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al pomodoro</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza al pomodoro ....</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 5.00 €.</p>

                        </div>
                    </div>
                </div>
                <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza2.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Filetto al basilico</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza con pomodorini e basilico</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.50 €.</p>

                        </div>
                    </div>
                </div>
                 <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza3.jpg" class="card-img-top" alt="..." style="height=250px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al salame</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza fette di salame piccanti </p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.00 €.</p>

                        </div>
                    </div>
                </div>

                 <div class="col" >
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza1.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al pomodoro</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza al pomodoro ....</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 5.00 €.</p>

                        </div>
                    </div>
                </div>
                <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza2.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Filetto al basilico</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza con pomodorini e basilico</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.50 €.</p>

                        </div>
                    </div>
                </div>
                 <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza3.jpg" class="card-img-top" alt="..." style="height=250px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al salame</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza fette di salame piccanti </p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.00 €.</p>

                        </div>
                    </div>
                </div>
                   

                   
                    

                </div>
                
            </main>
        </div>


    

    <footer class="border-top footer bg-dark text-muted">

        <div class="container">
            <h4 class="text-white text-start ">Code by Vinc-78</h4>
        </div>
    </footer>
    

</body>

</html>

Views/Home/Index2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewData["Title"] = "Home Page";
}
@section body {
   <div class="container" style="height=80vh">
            <main role="main" class="pb-3">

                <div class="row">

                <div class="col" >
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza1.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al pomodoro</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza al pomodoro ....</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 5.00 €.</p>

                        </div>
                    </div>
                </div>
                <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza2.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Filetto al basilico</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza con pomodorini e basilico</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.50 €.</p>

                        </div>
                    </div>
                </div>
                 <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza3.jpg" class="card-img-top" alt="..." style="height=250px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al salame</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza fette di salame piccanti </p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.00 €.</p>

                        </div>
                    </div>
                </div>

                 <div class="col" >
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza1.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al pomodoro</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza al pomodoro ....</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 5.00 €.</p>

                        </div>
                    </div>
                </div>
                <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza2.jpg" class="card-img-top" alt="..." style="height=150px!important">
                        <div class="card-body">
                            <h5 class="card-title">Filetto al basilico</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza con pomodorini e basilico</p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.50 €.</p>

                        </div>
                    </div>
                </div>
                 <div class="col" style="height=250px">
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/pizza3.jpg" class="card-img-top" alt="..." style="height=250px!important">
                        <div class="card-body">
                            <h5 class="card-title">Pizza al salame</h5>
                            <h5>Descrizione</h5>
                            <p class="card-text">Pizza fette di salame piccanti </p>
                            <h5>Prezzo</h5>
                            <p class="card-text mt-2"> 6.00 €.</p>

                        </div>
                    </div>
                </div>
                   

                   
                    

                </div>
                
            </main>
        </div>
}


@section prova {
    
    
    <ul>
        <li><a href="...">Ordina</a></li>
        <li><a href="...">Carello</a></li>
        <li><a href="...">Contattaci</a></li>

        
    </ul>


}

Views/Pizza/ErrorPage.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "la mia pizzeria model";
}



<h1> Pizza non trovata </h1>

Views/Pizza/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
    ViewData["Title"] = "la mia pizzeria model";
}
@model la_mia_pizzeria_static.Models.listaPizze


<div class="row">
                @foreach(var element in Model.pizzas)
                   {
                    <div class="col">
                            <div class="card">
                                <div class="card-img-top">
                                    <img class="imgIndex" src="@Url.Content(element.ImgPath)" alt="..." />												
                                </div>
                                <div class="card-body">
                                    <h2><a href="@Url.Action("Show", "Pizza", new{element.Id})">@element.Nome</a></h2>
                                    <h5 class="card-title">@element.Nome</h5>
                                    <p class="card-text">@element.Descrizione</p>
                                    <p>@element.Prezzo &euro</p>
                                </div>

                            </div>
                      </div>
                   }

</div>

Views/Pizza/Show.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "la mia pizzeria model";
}

@model la_mia_pizzeria_static.Models.Pizza

<h2 class=text-center>Descrizione della pizza che hai scelto</h2>
<h2><a href="@Url.Action("Index", "Pizza")">Torna a tutte le pizze</a></h2>

<div class="col">
    <div class="card">
        <div class="row">
            <div class="col-6">
                <div class="card-img-top">
                    <img id="showImg" src="@Url.Content(@Model.ImgPath)" alt="..." />
                </div>
            </div>
            <div class="col-6">
                <div class="card-body">

                    <h5 class="card-title">@Model.Nome</h5>
                    <p class="card-text">@Model.Descrizione</p>
                    <p>@Model.Prezzo &euro;</p>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <h1 class="text-center">La mia pizzeria</h1>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
   
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />


</head>
<body>
    <div class="row">
        <div class="col-3">
            <h1>Menu</h1>
             @RenderSection("prova")
             
        </div>

         <div class="col-9">
              @RenderSection("body")
           
        </div>

    </div>
    
</body>
</html>